# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b998881729b16be97547259f8242193704dd2c4646ff07a5b76887dc60623e7288ee6767cd9bd7456dbab6488cbd0bfa27a0014c7ac18cc2c8bdd2ecab8bdc

test:
  secret_key_base: 2c9ba55d89a179ecc8ff093b9b80a855767bf631966231b49427ac011391b5f20845242c286b586200d2844a81dd092067c7f0aaa498a5a2d1de6a5153a5befb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
